SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `WINSTON` DEFAULT CHARACTER SET latin1 COLLATE latin1_bin ;
USE `WINSTON`;

-- -----------------------------------------------------
-- Table `WINSTON`.`CODIGOSDACCU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WINSTON`.`CODIGOSDACCU` ;

CREATE  TABLE IF NOT EXISTS `CODIGOSDACCU` (
  `TI_CODIGOSDACCU_ID` TINYINT NOT NULL AUTO_INCREMENT ,
  `VA_CODIGO` CHAR(10) NOT NULL ,
  `VA_DESCRICAO` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`TI_CODIGOSDACCU_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_bin;


-- -----------------------------------------------------
-- Table `WINSTON`.`CCU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WINSTON`.`CCU` ;

CREATE  TABLE IF NOT EXISTS `CCU` (
  `BI_CCU_ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `TI_CODIGOSDACCU_ID` TINYINT NOT NULL ,
  `TX_DESCRICAO` TEXT NOT NULL ,
  `DT_DATAHORAINICIAL` DATETIME NOT NULL ,
  `DT_DATAGIRAFINAL` DATETIME NOT NULL ,
  PRIMARY KEY (`BI_CCU_ID`) ,
  CONSTRAINT `CCU_CODIGOSDACCU_FK`
    FOREIGN KEY (`TI_CODIGOSDACCU_ID` )
    REFERENCES `CODIGOSDACCU` (`TI_CODIGOSDACCU_ID` )
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_bin;

CREATE INDEX `CCU_CODIGOSDACCU_FK` ON `CCU` (`TI_CODIGOSDACCU_ID` ASC) ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
